name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ubuntu-clang-trinitycore:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/setup_ubuntu
      - name: Build tswow
        shell: bash
        run: npm run build noac

  windows-msvc-trinitycore:
    runs-on: windows-2022
    steps:
      # Build
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/setup_windows
      - name: Build tswow
        run: npm run build-release clean-archives noac tracy=*
      - name: Publish release
        if: github.ref == 'refs/heads/master'
        run: node .github/scripts/upload-release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
